### PR TITLE
fix(react): Add example using Next.js

### LINKED ISSUE #103: Usage with Next.js
Next.js handles React and React DOM for you. How would you add this to a Next.js project?

### PR DESCRIPTION
**Pull request by stephenmathieson**
This patch adds an example of using `@axe-core/react` and [`Next.js`](https://nextjs.org/) together. The existing `example` was moved to `examples/shadow-dom` in order to make this happen.

The example Next.js app was created by simply doing `npx create-next-app`. The only differences from its default output and our version is Prettier/ESLint tweaks and a custom `pages/_app.js` file which loads axe.

Closes #103

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**

- [x] Code is reviewed for security

### CODE REVIEW

**Comment by stephenmathieson** [comment]
Seems that `axe-linter` detected several accessibility issues in the example Next.js app. While this a great, fixing them would also render the example useless. Should I fix them or leave them alone?

**Comment by michael-siek** [comment]
@stephenmathieson we could just add a glob to `.github/axe-linter.yml` and add 
```yml
  - packages/react/example/next.js/**/*
```

**Comment by stephenmathieson** [comment]
Sounds good, thanks! 👍

**Review by michael-siek — APPROVED** [review]
LGTM

**Pull request merged**
