### PR TITLE
fix(webdriverjs): Recursively find <frame> 

### PR DESCRIPTION
**Pull request by yokra9**
Fixed to recursively find `<frame>`  and inject a script into them, not only `<iframe>`.

`<frame>` is deprecated in HTML5, but sometimes use in bad examples when teach modern & accessible coding.
ex: https://barrierfree.nict.go.jp/accessibility/whatsacs/sample/level0/index.html

Thanks!

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**

- [x] Code is reviewed for security

### CODE REVIEW

**Comment by michael-siek** [comment]
Hi, @yokra9 do you mind providing tests for this fix.

**Comment by yokra9** [comment]
@michael-siek thanks for comment! added 2 commits for providing tests for this fix.

* added unit test for this fix.
  + revive test fixtures, `inner-configure-frame.html`, which might have removed unintentionally.
* removed unused test fixtures.

**Comment by WilcoFiers** [comment]
@yokra9 I just wanted to let you know we're still looking to see if we want this change added. As you pointed out, frames were deprecated years ago. Axe has never supported them. We're currently working to improve consistency between the various axe packages we maintain. That includes whether or not they support frames. If we add frame support to webdriverjs, we need to do it to webdriverio, puppeteer, cypress, Java/Ruby/C# selenium, Ruby Watir, etc. That is a fairly substantial amount of work.

I very much do appreciate you setting up this PR. And I apologies for not noticing this before you made additional commits to it. I'm going to bring this up internally and will get back to you soon.

**Comment by michael-siek** [comment]
Thank you very much for your contribution @yokra9.

**Review by michael-siek — APPROVED** [review]

**Pull request merged**
