### PR TITLE
feat(playwright): distributes both ESM and CJS modules

### PR DESCRIPTION
**Pull request by akornmeier**
Fixes: [#670, #601]

- add: tsup package to handle building/exporting both ESM and CJS modules
- update: README to include ESM and CJS import/require techniques for users
- update: mocha to work w/ ES modules

### CODE REVIEW

**Comment by stephenmathieson** [comment]
Sup Tony 👋

**Comment by akornmeier** [comment]
> Sup Tony 👋

@stephenmathieson - Hey Stephen. 

image

**Review by straker — APPROVED** [review]
Thanks for the fixes!

**Comment by straker** [comment]
Approved for security

**Comment by straker** [comment]
Since this is a feat and we have a planned patch release soon, we're going to hold off on merging this for now. Will reevaluate once we get the patch out.

**Comment by akornmeier** [comment]
> Since this is a feat and we have a planned patch release soon, we're going to hold off on merging this for now. Will reevaluate once we get the patch out.

I understand, however I could change change the commit to a fix since this is technically fixing an existing issue and not adding extra functionality. Let me know what you think the best path forward would be? 

What would the ETA for the changes to land if they don't make it into the patch release?

**Comment by straker** [comment]
We want to keep this a `feat` since we are adding official support for modules where we didn't have it before. As for a timeline, axe-core is currently working on a 4.7 release, but I'm not sure on the deadline of it yet, but it will be some time.

**Comment by straker** [comment]
After talking to @AdnoC and @michael-siek, and trying to [update all of our packages to do this technique](678), we've decided to not do this approach as it isn't nearly as nice as we would have hoped and requires converting all the files to CJS. We'll instead work on what a lot of other libraries have done which is moving away from a default export and only supporting named exports.

For now, we'll support `require` using either a default or a named export, but `import` will be a named export only. For the next major release we'll remove the default export for require.

**Comment by michael-siek** [comment]
Closing no longer required

**Pull request closed without merging**
