### PR TITLE
fix(playwright): use @playwright/test

### PR DESCRIPTION
**Pull request by dargmuesli**
Resolves the error `Please install @playwright/test package to use Playwright Test.`.
See https://github.com/microsoft/playwright/issues/23098.

Also removes a few unused variables.

### CODE REVIEW

**Comment by stephenmathieson** [comment]
@dargmuesli I was dealing with this issue in a different repository yesterday. I completely understand your pain.

However, I don't think having a peer dep on `@playwright/test` is the correct solution. Users may not be using the package, so we don't want to force them to have it installed. Can we simply have a peer dependency on `playwright-core` instead?

**Comment by dargmuesli** [comment]
Thank you for the feedback! :heart:
I'd need to test that, I think I'll get around to do this either today or within this week.
Feel free to tinker with my branch though if you have quick ideas!

**Comment by dargmuesli** [comment]
Using `playwright-core` as peer dependency worked as well for me! :) I've updated the code.

I think why the ci pipeline fails is not an error on my part, is it? Seems it cannot extract the downloaded browser image.

**Review by stephenmathieson — APPROVED** [review]
LGTM, but let's let a maintainer give the final OK.

----

Got the OK from @michael-siek 👍

**Comment by stephenmathieson** [comment]
Reviewed for security

**Comment by Zidious** [comment]
- [ ] Reviewed for security

**Comment by stephenmathieson** [comment]
Thanks @dargmuesli! I'm not sure when the next public/stable release is planned for. In the meantime, you can `npm install @axe-core/playwright@next` in your project.

**Pull request merged**
