### PR TITLE
feat(cli): improve error message on script timeout

### PR DESCRIPTION
**Pull request by not-my-profile**
Previously a script timeout error just displayed a stack trace without any information on the current timeout or how to change the timeout.

### CODE REVIEW

**Review by stephenmathieson — COMMENTED** [review]
> If you like these changes please merge them without squashing.

We squash all PRs. If you want to make multiple unrelated changes, open multiple unrelated PRs.

**Comment by not-my-profile** [comment]
I think there are certain cases where it makes sense to make an exception (e.g. larger refactors). In this case though it was easy for me to split up the other change into #683.

**Comment by Zidious** [comment]
Hey @not-my-profile, 

Apologies for the delay, once we get CI running on your PR we'll be able to merge it in. 

Thanks again!

**Review by straker — APPROVED** [review]
Thanks again for the contribution.

Reviewed for security.

**Pull request merged**
